/* generated by pull.js */
import _js from './userscript.js';
import _css from '!css-loader?{"esModule":false}!./terminal.css';
import _css2 from '!css-loader!../../ui/bottom-panel/bottom-panel.css';
import _asset from '!url-loader?{"esModule":false}!./logo.svg';
export const resources = {
  'userscript.js': _js,
  'terminal.css': _css,
  'bottom-panel.css': _css2,
  'logo.svg': _asset
};
