/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "AI integration into the editor",
  "description": "Adds AI integration into the editor including code completion, code generation, sprite generation, background generation, and more.\n\n\nDISCLAIMER: We do not store any request data or your API keys. Your API keys are only sent with requests and remain fully stored locally on your computer. All models we use are free, ensuring no charges apply. However, for added security, we recommend setting restrictions on your API keys.",
  "info": [
    {
      "text": "Credits: CodeTorch.net"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "id": "GeminiAPIKey",
      "name": "Google Gemini API Key",
      "type": "long_password",
      "default": "",
    },
    {
      "id": "OpenRouterAPIKey",
      "name": "OpenRouter API Key",
      "type": "long_password",
      "default": "",
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
