/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "My Block Plus",
  "description": "Enhance the functionality and flexibility of custom blocks.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "info": [
    {
      "type": "info",
      "text": "This plugin will automatically load the \"My Block Plus\" extension when creating a project.",
      "id": "info"
    },
    {
      "type": "info",
      "text": "Warning: It loads a new extension, it may not be removed.",
      "id": "warn"
    }
  ],
  "credits": [
    {
      "name": "SharkPool"
    },
    {
      "name": "CST1229"
    },
    {
      "name": "0znzw"
    },
    {
      "name": "KOSHINO",
      "link": "https://github.com/KOSHINOawa"
    },
    {
      "name": "笑小朗",
    }
  ],
  "dynamicDisable": true,
  "tags": ["new", "rw"],
  "settings": [
    {
      "type": "boolean",
      "id": "hideCustomBlocks",
      "name": "Hide Custom Blocks",
      "default": false
    }
  ]
};
export default manifest;
