/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Quotes",
  "description": "Displays a \"Quote of the Day\" or a random phrase in the editor's status bar and provides a settings panel to adjust the rotation interval.",
  "credits": [
    {
      "name": "笑小朗",
      "link": ""
    },
    {
      "name": "https://developer.hitokoto.cn/",
      "link": "https://developer.hitokoto.cn/"
    },
    {
      "name": "https://card.gudong.site/",
      "link": "https://card.gudong.site/"
    },
    {
      "name": "https://www.jinrishici.com/",
      "link": "https://www.jinrishici.com/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [],
  "settings": [
    {
      "dynamic": true,
      "name": "Enable Quotes",
      "id": "enable_daily_quote",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Switch interval (seconds)",
      "id": "interval",
      "type": "positive_integer",
      "default": 5
    },
    {
      "dynamic": true,
      "name": "Display mode",
      "id": "display_mode",
      "type": "select",
      "default": "sequential",
      "potentialValues": [
        {
          "id": "sequential",
          "name": "Sequential"
        },
        {
          "id": "random",
          "name": "Random"
        }
      ]
    },
    {
      "dynamic": true,
      "name": "Quote Library",
      "id": "quote_library",
      "type": "select",
      "default": "local",
      "potentialValues": [
        {
          "id": "local",
          "name": "Local"
        },
        {
          "id": "hitokoto",
          "name": "A word"
        },
        {
          "id": "gudong",
          "name": "Notes on Ancient Movements"
        },
        {
          "id": "jinrishici",
          "name": "Poem of the Day"
        }
      ]
    },
    {
      "dynamic": false,
      "name": "Custom quotes (one sentence per line)",
      "id": "custom_quotes",
      "type": "string",
      "multiline": true,
      "rows": 10,
      "default": "Welcome to PotentiaMod. \nYou need to straight out power and responsibility. \nIs that OK that we will use some shampoo? \nFun fact: Dragons ay plan on the WORLD DOMINATION!"
    }
  ],
  "tags": [
    "rw",
    "ui",
    "daily",
    "quote"
  ],
  "enabledByDefault": true
};
export default manifest;
